### ISSUE TITLE
What is the problem that can't write to the mysql database！

### ISSUE THREAD

**Issue by dick-nux** [quadrantsec/meer#6]
When i use ./configure install  meer ，No data when running。I suspect that meer.yml there is a problem , but I don't know where the problem is,who can give pointers me ,tks!。

*] [09/26/2021 08:38:58] Dropping privileges! [UID: 998 GID: 1002]
[*] [09/26/2021 08:38:58] Classifications file loaded [/etc/suricata/classification.config].
[*] [09/26/2021 08:38:58]
[*] [09/26/2021 08:38:58] Decode 'json'          : enabled
[*] [09/26/2021 08:38:58] Decode 'metadata'      : enabled
[*] [09/26/2021 08:38:58] Decode 'flow'          : enabled
[*] [09/26/2021 08:38:58] Decode 'http'          : enabled
[*] [09/26/2021 08:38:58] Decode 'tls'           : enabled
[*] [09/26/2021 08:38:58] Decode 'ssh'           : enabled
[*] [09/26/2021 08:38:58] Decode 'smtp'          : enabled
[*] [09/26/2021 08:38:58] Decode 'email'         : enabled
[*] [09/26/2021 08:38:58] Decode 'bluedot'       : disabled
[*] [09/26/2021 08:38:58]
[*] [09/26/2021 08:38:58] Fingerprint support    : enabled
[*] [09/26/2021 08:38:58] Health updates         : disabled
[*] [09/26/2021 08:38:58]
[*] [09/26/2021 08:38:58] Waldo loaded. Current position: 0
[*] [09/26/2021 08:38:58]
[*] [09/26/2021 08:38:58] --[ External information ]-----------------------------------------
[*] [09/26/2021 08:38:58]
[*] [09/26/2021 08:38:58] Default external program: /usr/local/bin/external_program
[*] [09/26/2021 08:38:58] Execute on 'security-ips' policy: enabled
[*] [09/26/2021 08:38:58] Execute on 'balanced-ips' policy: enabled
[*] [09/26/2021 08:38:58] Execute on 'connectivity-ips' policy: enabled
[*] [09/26/2021 08:38:58] Execute on 'max-detect-ips' policy: enabled
[*] [09/26/2021 08:38:58]
[*] [09/26/2021 08:38:58] --[ Fingerprinting information ]---------------------------------
[*] [09/26/2021 08:38:58]
[*] [09/26/2021 08:38:58] Fingerprinting : enabled
[*] [09/26/2021 08:38:58] Fingerprint log file : /var/log/meer/fingerprint.eve
[*] [09/26/2021 08:38:58]
[*] [09/26/2021 08:38:58] --[ Meer engine information ]-------------------------------------
[*] [09/26/2021 08:38:58]
[*] [09/26/2021 08:38:58] Successfully opened /var/log/suricata/alert.json.
[*] [09/26/2021 08:38:58] Ingesting data. Working........
[*] [09/26/2021 08:38:58] Read in 0 lines
[*] [09/26/2021 08:38:58] Waiting for new data......

**Comment by quadrantsec** [comment]
*[*] [09/26/2021 08:38:58] Read in 0 lines

Your EVE file has no data in it to ingest.

**Comment by beave** [comment]
Also, disable "external" if you aren't using it.
